# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-03 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awaards', '0003_auto_20190703_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_photo',
            new_name='profile_pic',
        ),
    ]
