# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-04 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaards', '0006_auto_20190704_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='average_vote',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
