# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-04 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awaards', '0007_rating_average_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='average_vote',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awaards.Project'),
        ),
    ]
